---
swagger: "2.0"
info:
  title: Rick and Morty
  version: 1.0.0
  description: É uma série de animação adulta norte-americana de comédia e ficção
    científica.
  contact:
    email: erick.peiker@verity.com.br
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
consumes:
- application/json
produces:
- application/json
paths:
  /personagens:
    get:
      responses:
        "200":
          description: Successful response - returns an array of `Personagens` entities.
          schema:
            type: array
            items:
              $ref: '#/definitions/Personagens'
      operationId: getPersonagens
      summary: List All Personagens
      description: Gets a list of all `Personagens` entities.
    post:
      parameters:
      - name: body
        description: A new `Personagens` to be created.
        schema:
          $ref: '#/definitions/Personagens'
        in: body
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createPersonagens
      summary: Create a Personagens
      description: Creates a new instance of a `Personagens`.
  /personagens/{personagensId}:
    get:
      responses:
        "200":
          description: Successful response - returns a single `Personagens`.
          schema:
            $ref: '#/definitions/Personagens'
      operationId: getPersonagensById
      summary: Get a Personagens
      description: Gets the details of a single instance of a `Personagens`.
    put:
      parameters:
      - name: body
        description: Updated `Personagens` information.
        schema:
          $ref: '#/definitions/Personagens'
        in: body
        required: true
      responses:
        "202":
          description: Successful response.
      operationId: updatePersonagens
      summary: Update a Personagens
      description: Updates an existing `Personagens`.
    delete:
      responses:
        "204":
          description: Successful response.
      operationId: deletePersonagens
      summary: Delete a Personagens
      description: Deletes an existing `Personagens`.
    parameters:
    - name: personagensId
      description: A unique identifier for a `Personagens`.
      in: path
      required: true
      type: string
  /episodios:
    get:
      responses:
        "200":
          description: Successful response - returns an array of `Episodios` entities.
          schema:
            type: array
            items:
              $ref: '#/definitions/Episodios'
      operationId: getEpisodios
      summary: List All Episodios
      description: Gets a list of all `Episodios` entities.
    post:
      parameters:
      - name: body
        description: A new `Episodios` to be created.
        schema:
          $ref: '#/definitions/Episodios'
        in: body
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createEpisodios
      summary: Create a Episodios
      description: Creates a new instance of a `Episodios`.
  /episodios/{episodiosId}:
    get:
      responses:
        "200":
          description: Successful response - returns a single `Episodios`.
          schema:
            $ref: '#/definitions/Episodios'
      operationId: getEpisodiosById
      summary: Get a Episodios
      description: Gets the details of a single instance of a `Episodios`.
    put:
      parameters:
      - name: body
        description: Updated `Episodios` information.
        schema:
          $ref: '#/definitions/Episodios'
        in: body
        required: true
      responses:
        "202":
          description: Successful response.
      operationId: updateEpisodios
      summary: Update a Episodios
      description: Updates an existing `Episodios`.
    delete:
      responses:
        "204":
          description: Successful response.
      operationId: deleteEpisodios
      summary: Delete a Episodios
      description: Deletes an existing `Episodios`.
    parameters:
    - name: episodiosId
      description: A unique identifier for a `Episodios`.
      in: path
      required: true
      type: string
  /lugares:
    get:
      responses:
        "200":
          description: Successful response - returns an array of `Lugares` entities.
          schema:
            type: array
            items:
              $ref: '#/definitions/Lugares'
      operationId: getLugares
      summary: List All Lugares
      description: Gets a list of all `Lugares` entities.
    post:
      parameters:
      - name: body
        description: A new `Lugares` to be created.
        schema:
          $ref: '#/definitions/Lugares'
        in: body
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createLugares
      summary: Create a Lugares
      description: Creates a new instance of a `Lugares`.
  /lugares/{lugaresId}:
    get:
      responses:
        "200":
          description: Successful response - returns a single `Lugares`.
          schema:
            $ref: '#/definitions/Lugares'
      operationId: getLugaresById
      summary: Get a Lugares
      description: Gets the details of a single instance of a `Lugares`.
    put:
      parameters:
      - name: body
        description: Updated `Lugares` information.
        schema:
          $ref: '#/definitions/Lugares'
        in: body
        required: true
      responses:
        "202":
          description: Successful response.
      operationId: updateLugares
      summary: Update a Lugares
      description: Updates an existing `Lugares`.
    delete:
      responses:
        "204":
          description: Successful response.
      operationId: deleteLugares
      summary: Delete a Lugares
      description: Deletes an existing `Lugares`.
    parameters:
    - name: lugaresId
      description: A unique identifier for a `Lugares`.
      in: path
      required: true
      type: string
definitions:
  Personagens:
    title: Root Type for Personagens
    description: ""
    type: object
    properties:
      status:
        type: string
      url:
        type: string
      codigo:
        format: int32
        type: integer
      genero:
        type: string
      nome:
        type: string
      especie:
        type: string
      tipo:
        type: string
      episodios:
        type: array
        items:
          type: string
    example:
      codigo: 2
      nome: Morty Smith
      status: Alive
      especie: Human
      tipo: ""
      genero: Male
      episodios:
      - https://rickandmortyapi.com/api/episode/1
      - https://rickandmortyapi.com/api/episode/2
      url: https://rickandmortyapi.com/api/character/2
  Episodios:
    title: Root Type for Episodios
    description: ""
    type: object
    properties:
      id:
        format: int32
        type: integer
      name:
        type: string
      air_date:
        type: string
      episode:
        type: string
      characters:
        type: array
        items:
          type: string
      url:
        type: string
      created:
        format: date-time
        type: string
    example:
      id: 28
      name: The Ricklantis Mixup
      air_date: "September 10, 2017"
      episode: S03E07
      characters:
      - https://rickandmortyapi.com/api/character/1
      - https://rickandmortyapi.com/api/character/2
      url: https://rickandmortyapi.com/api/episode/28
      created: 2017-11-10T12:56:36.618Z
  Lugares:
    title: Root Type for Lugares
    description: ""
    type: object
    properties:
      id:
        format: int32
        type: integer
      name:
        type: string
      type:
        type: string
      dimension:
        type: string
      residents:
        type: array
        items:
          type: string
      url:
        type: string
      created:
        format: date-time
        type: string
    example:
      id: 1
      name: Earth
      type: Planet
      dimension: Dimension C-137
      residents:
      - https://rickandmortyapi.com/api/character/1
      - https://rickandmortyapi.com/api/character/2
      url: https://rickandmortyapi.com/api/location/1
      created: 2017-11-10T12:42:04.162Z
